# BEGIN_KITTY_THEME
# Bright Lights
include current-theme.conf
# END_KITTY_THEME

background_opacity         0.8
dynamic_background_opacity yes
background_blur 1
font_size 11

remember_window_size  no
initial_window_width  850
initial_window_height 500

# Some extra keybinds for a terminal code editor
# Need these binds for selection
map ctrl+shift+left  no_op
map ctrl+shift+right no_op

# New terminal for code editor
map ctrl+shift+enter launch --type=window --cwd=current --location=hsplit --bias=30