# BEGIN_KITTY_THEME
# Bright Lights
include current-theme.conf
# END_KITTY_THEME


background_opacity         0.8
dynamic_background_opacity yes
background_blur 1
font_size 11

# I prefer new terminals to open in the same dir
map ctrl+shift+enter launch --type=window --cwd=current

# These are part of my helix keybinds
map ctrl+shift+down launch --type=window --cwd=current --location=hsplit --bias=30

map ctrl+shift+k first_window
map ctrl+shift+j second_window
