version = 1

[image]

[image.loading]
initial.lazy_loading = false
gui.lazy_loading = true

[image.optimizations]
mode = "default"

monitor_downsampling = { enabled = true, strength = 1.4 }
experimental_consume_pixels_during_gpu_upload = true
experimental_dynamic_sampling = false
experimental_multi_threaded_sampling = true

[image.backend]
decoder = "image-rs"

[ui]

[ui.controls]
hide = true

magnification = true

[ui.viewport]
padding = 2.0
zoom_into_cursor = true
fit_to_window = true
animate_fit_to_window = true
animate_reset = true

[ui.selection_menu]
show_open_image_button = true

[key_binds]
show_image_info = "I"
show_extra_image_info = "CTRL+I"
reset_viewport = "R"
show_ui_controls = "C"

[misc]
# override_monitor_size = {width = 1280, height = 720}

[misc.experimental]
show_ui_modes_popup = true

