[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "codebook"]

[[language]]
name = "markdown"
language-servers = ["marksman", "codebook"]
