# BEGIN_KITTY_THEME
# Rosé Pine
include current-theme.conf
# END_KITTY_THEME


background_opacity         0.8
dynamic_background_opacity yes
background_blur 1

remember_window_size  no
initial_window_width  850
initial_window_height 500

# I prefer new terminals to open in the same dir
# map ctrl+shift+enter launch --type=window --cwd=current

# Some extra keybinds for a terminal code editor
# Need these binds for selection
map ctrl+shift+left  no_op
map ctrl+shift+right no_op

# New terminal for code editor
map ctrl+shift+enter launch --type=window --cwd=current --location=hsplit --bias=30

# Switch forcus between code editor and kitty terminal
#map ctrl+shift+k first_window
#map ctrl+shift+j second_window
